name: Raise an issue with a Flexibility Market Rule
description: Log an issue with an existing Flexibility Market Rule.
title: "Flexibility Market Rule Issue: [Title of Issue]"
labels: [Flexibility Market Rule Issue]
projects: FMR Lifecycle
assignees: []
body:
  - type: input
    id: Issue Name
    attributes:
      label: Issue Name
      description: Name of the Issue you are raising
      placeholder: 
    validations:
      required: true
      
  - type: input
    id: rule_name
    attributes:
      label: Rule Name
      description: Name of the rule you want to amend (e.g. Standard Agreement).
      placeholder: 
    validations:
      required: true

  - type: input
    id: rule_id
    attributes:
      label: Rule ID
      description: ID of the rule you want to amend, leave blank if unkown.
      placeholder: e.g. MF-FMR-002
    validations:
      required: false

  - type: input
    id: proposer
    attributes:
      label: Proposing Organisation or Individual
      description: Who is proposing this change?
      placeholder: e.g. DSO X or FSP B
    validations:
      required: true

  - type: textarea
    id: Issue
    attributes:
      label: Description of the Issue
      description: Describe the problem to be addressed.
      placeholder: |
        The clauses on data protection differ across organisations
    validations:
      required: true

  - type: textarea
    id: Impact
    attributes:
      label: Description of the Impact
      description: What is the impact of the issue?
      placeholder: |
        Additional cost scrutinizing all the requirements and implementating the various obligations
    validations:
      required: false
      
  - type: textarea
    id: Dependencies
    attributes:
      label: Known Dependencies
      description: what else might need to be delivered before this can be resolved
      placeholder: |
        Registration process alignment
    validations:
      required: false
      
  - type: textarea
    id: Solution
    attributes:
      label: Description of potential Solutions
      description: How could we solve the issue?
      placeholder: |
        Develop aligned requirements in the DSO service terms
    validations:
      required: false

  - type: input
    id: attachments
    attributes:
      label: Supporting Documents or Links
      description: Add links to draft wording, diagrams, or prior discussions.
      placeholder: 
    validations:
      required: false
