name: Propose a design change or a new requirement to the FMAR design
description: FMAR Design Change or New Requirement Proposal.
title: '[Design Change/New Requirement]: A brief title for your proposal'
labels: ['design', 'requirement', 'triage-needed']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ### **Thank You for Contributing to FMAR!**
        This template will help you structure your proposal for a design change or a new requirement. Please fill out the sections below to the best of your ability.
    id: submitted_by
    attributes:
      label: Submitted by
      placeholder: Full name or GitHub handle
    validations:
      required: true

  - type: input
    id: organisation
    attributes:
      label: Organisation
      placeholder: Name of organisation (if applicable)
    validations:
      required: false

  - type: textarea
    id: problem_statement
    attributes:
      label: 2. Problem Statement / Opportunity
      description: |
        Describe the problem this proposal solves or the opportunity it creates. 
        Please use the "As a [persona], I want/need to [do something], so that [I can achieve a benefit]" format if possible.
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: 3. Proposed Solution / Change
      description: Briefly describe your proposed solution or change at a high level.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### 4. [Self-Scoring Matrix](https://github.com/Mez-Elexon/Market-Facilitator-FMAR/blob/main/docs/Market_Facilitator/FMAR_Design/Programme_Level/self-scoring-matrix.md) 
        Please score each criterion from **1 (Low)** to **3 (High)** and justify your score. This helps prioritise and assess your proposal.

  - type: textarea
    id: scoring_matrix
    attributes:
      label: Self-Scoring Matrix
      value: |
        | Criterion | Self-Score (1-3) | Justification & Evidence |
        | --- | --- | --- |
        | **Strategic Alignment** |  |  |
        | **Industry Value & Impact** |  |  |
        | **Urgency & Dependencies** |  |  |
        | **Implementation Clarity & Simplicity** |  |  |
        | **Standardisation & Interoperability** |  |  |
        | **Total Score (out of 15)** |  |  |
      render: markdown

  - type: textarea
    id: supporting_evidence
    attributes:
      label: 5. Supporting Evidence
      description: Provide links to documents, diagrams, or other sources that support your proposal.
      placeholder: |
        * Link 1
        * Link 2
    validations:
      required: false

  - type: textarea
    id: impacted_artefacts
    attributes:
      label: 6. Impacted FMAR Artefacts
      description: |
        Please list any FMAR artefacts that would need to be updated if this proposal is implemented.
        For example: Use Case IDs, Data Product Definitions, Interface Specs, Ontologies, or Workshop Outputs.
      placeholder: |
        * UC-02.01: Register Asset
        * Interface Spec: Asset Registration API v1.2
        * Data Product: asset-metadata-core
        * Ontology concept: fmar:ControllableUnit
    validations:
      required: false



  - type: textarea
    id: additional_context
    attributes:
      label: 7. Additional Context (Optional)
      description: Any other context the FMAR Architecture Team should know when reviewing this proposal.
    validations:
      required: false
