---
name: Propose a Design Change or New Requirement to the FMAR Design
description: Submit a proposal to change or add a requirement to the FMAR design.
title: "[Design Change/New Requirement]: [Title of Proposal]"
labels: ['Flexibility Market Rule Issue', 'FMAR Module: ARM', 'FMAR Module: SPUM', 'FMAR Module: PSQM', 'FMAR Module: GICM']
projects: ["elexon-data/1"]
assignees: []


body:
  - type: input
    id: proposer
    attributes:
      label: Proposing Organisation or Individual
      description: Who is proposing this change?
      placeholder: e.g. DSO X or FSP B
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: Description of the Problem or Opportunity
      description: >
        What problem does this solve, or what opportunity does it create?  
        Use the format: "As a [persona], I want to [do something], so that [outcome/benefit]."
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Description of the Proposed Change or Requirement
      description: What is your high-level proposal? What would be different if this were implemented?
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Self-Scoring Matrix  
        Please score your proposal using [this scoring guide](https://github.com/Mez-Elexon/Market-Facilitator-FMAR/blob/main/docs/Market_Facilitator/FMAR_Design/Programme_Level/self-scoring-matrix.md).  
        This helps the FMAR Architecture Team assess strategic fit, urgency, and value.

  - type: textarea
    id: scoring_matrix
    attributes:
      label: Self-Scoring Matrix (use table format)
      value: |
        | Criterion | Self-Score (1-3) | Justification & Evidence |
        | --- | --- | --- |
        | **Strategic Alignment** |  |  |
        | **Industry Value & Impact** |  |  |
        | **Urgency & Dependencies** |  |  |
        | **Implementation Clarity & Simplicity** |  |  |
        | **Standardisation & Interoperability** |  |  |
        | **Total Score (out of 15)** |  |  |
      render: markdown
    validations:
      required: false

  - type: textarea
    id: impacted_artefacts
    attributes:
      label: Impacted FMAR Artefacts
      description: |
        Which FMAR artefacts would need updating if this change is accepted?  
        e.g. Use Case IDs
      placeholder: |
        * UC-02.01: Register and Validate Asset  
    validations:
      required: false

  - type: textarea
    id: supporting_evidence
    attributes:
      label: Supporting Documents or Links
      description: Add links to draft wording, diagrams, data, or prior discussions.
      placeholder: |
        * https://example.com/use-case-doc  
        * https://github.com/elexon-data/Market-Facilitator/discussions
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context (Optional)
      description: Any other background or considerations the FMAR Architecture Team should be aware of?
    validations:
      required: false
